#!/bin/sh
# Checks if plex is currently serving media to any user.
# Mark Blakeney, Jul 2020.

MYTOKEN="$1"
PORT=${2:-32400}

nsessions=$(curl -s "localhost:$PORT/status/sessions?X-Plex-Token=$MYTOKEN" |
    sed -n "s/.*MediaContainer size=\"\(.*\)\".*/\1/p")

[ "$nsessions" -gt 0 ] && exit 254
exit 0
